language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "Jhon Zhu"
  - git config user.email "zzycjcg@qq.com"
  - git add .
  - git commit -m "add post"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/zzycjcg/zzycjcg.github.io.git
   
